-- Catalogo de produtos, com o estoque separado em disponivel e reservado.

CREATE TABLE produtos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(140)   NOT NULL,
    descricao          VARCHAR(2000),
    preco              NUMERIC(12, 2) NOT NULL,
    estoque_disponivel INTEGER        NOT NULL DEFAULT 0,
    estoque_reservado  INTEGER        NOT NULL DEFAULT 0,
    ativo              BOOLEAN        NOT NULL DEFAULT TRUE,

    CONSTRAINT produtos_preco_nao_negativo CHECK (preco >= 0),

    -- Ultima linha de defesa do estoque. A aplicacao ja valida antes de reservar,
    -- mas entre a validacao e a gravacao existe uma janela em que outra transacao
    -- pode levar a mesma unidade. Se isso acontecer, a transacao perdedora morre
    -- aqui, no banco, em vez de gravar estoque negativo.
    CONSTRAINT produtos_estoque_disponivel_nao_negativo CHECK (estoque_disponivel >= 0),
    CONSTRAINT produtos_estoque_reservado_nao_negativo CHECK (estoque_reservado >= 0)
);

-- Nome unico sem diferenciar maiusculas: "Teclado Mecanico" e "teclado mecanico"
-- sao o mesmo produto para quem compra, entao o banco tambem trata assim.
CREATE UNIQUE INDEX produtos_nome_unico ON produtos (LOWER(nome));
