-- Usuarios e seus papeis.

CREATE TABLE usuarios (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(120) NOT NULL,
    -- Armazenado sempre em minusculas pela aplicacao; o indice unico abaixo
    -- garante no banco que "Joao@x.com" e "joao@x.com" nao coexistam.
    email      VARCHAR(180) NOT NULL,
    -- Hash BCrypt: 60 caracteres. O campo e maior para tolerar troca de algoritmo.
    senha_hash VARCHAR(100) NOT NULL,
    papel      VARCHAR(20)  NOT NULL,
    criado_em  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT usuarios_papel_valido CHECK (papel IN ('CLIENTE', 'ADMIN'))
);

CREATE UNIQUE INDEX usuarios_email_unico ON usuarios (LOWER(email));
