-- Pedidos e seus itens.

CREATE TABLE pedidos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT         NOT NULL REFERENCES usuarios (id),
    status             VARCHAR(30)    NOT NULL,
    valor_total        NUMERIC(12, 2) NOT NULL,
    -- Chave enviada pelo cliente no cabecalho Idempotency-Key.
    chave_idempotencia VARCHAR(80)    NOT NULL,
    criado_em          TIMESTAMPTZ    NOT NULL,

    CONSTRAINT pedidos_valor_total_nao_negativo CHECK (valor_total >= 0),
    CONSTRAINT pedidos_status_valido CHECK (status IN (
        'AGUARDANDO_PAGAMENTO', 'PAGO', 'SEPARANDO', 'ENVIADO', 'ENTREGUE', 'CANCELADO', 'REEMBOLSADO'
    ))
);

-- O coracao da idempotencia de entrada.
--
-- A aplicacao consulta esta chave antes de criar, mas entre a consulta e o
-- INSERT existe uma janela: duas requisicoes simultaneas com a mesma chave
-- passam as duas pela consulta sem achar nada. Este indice fecha a janela — a
-- segunda transacao morre aqui, e a aplicacao devolve o pedido que a primeira
-- criou, em vez de criar um segundo.
--
-- A chave e unica POR USUARIO, nao globalmente: fosse global, mandar a chave de
-- outra pessoa devolveria o pedido dela.
CREATE UNIQUE INDEX pedidos_idempotencia_por_usuario ON pedidos (usuario_id, chave_idempotencia);

CREATE INDEX pedidos_por_usuario ON pedidos (usuario_id, criado_em DESC);

CREATE TABLE itens_pedido (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT         NOT NULL REFERENCES pedidos (id) ON DELETE CASCADE,
    produto_id     BIGINT         NOT NULL REFERENCES produtos (id),
    -- Nome e preco sao copias do momento da compra, nao leituras do catalogo.
    -- Sem elas, um reajuste ou uma renomeacao reescreveria pedidos antigos.
    nome_produto   VARCHAR(140)   NOT NULL,
    quantidade     INTEGER        NOT NULL,
    preco_unitario NUMERIC(12, 2) NOT NULL,

    CONSTRAINT itens_pedido_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT itens_pedido_preco_nao_negativo CHECK (preco_unitario >= 0)
);

CREATE INDEX itens_pedido_por_pedido ON itens_pedido (pedido_id);
