-- Cobrancas criadas no gateway externo.

CREATE TABLE pagamentos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Um pedido tem no maximo uma cobranca. O UNIQUE nao e decoracao: ele fecha
    -- a janela entre "consultei e nao havia cobranca" e "criei a cobranca",
    -- impedindo que duas requisicoes simultaneas cobrem o cliente duas vezes.
    pedido_id     BIGINT         NOT NULL UNIQUE REFERENCES pedidos (id),
    -- Identificador da cobranca no gateway (pi_... no Stripe). E a chave para
    -- reconciliar os dois lados, e por onde o webhook da Etapa 7 acha o pedido.
    id_externo    VARCHAR(120)   NOT NULL UNIQUE,
    status        VARCHAR(20)    NOT NULL,
    valor         NUMERIC(12, 2) NOT NULL,
    criado_em     TIMESTAMPTZ    NOT NULL,
    atualizado_em TIMESTAMPTZ    NOT NULL,

    CONSTRAINT pagamentos_valor_positivo CHECK (valor > 0),
    CONSTRAINT pagamentos_status_valido CHECK (status IN ('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO'))
);
