-- Registro dos eventos do gateway ja consumidos.
--
-- Esta tabela nao guarda regra de negocio: ela existe para ter uma restricao de
-- unicidade sobre o identificador do evento. Gravada na MESMA transacao que
-- aplica o efeito, e ela que torna o processamento idempotente — a segunda
-- entrega do mesmo evento colide aqui e a transacao inteira e desfeita, sem o
-- estoque baixar duas vezes nem o pedido ser confirmado de novo.

CREATE TABLE eventos_processados (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- O identificador que o gateway da ao evento (evt_... no Stripe).
    id_externo    VARCHAR(120) NOT NULL UNIQUE,
    tipo          VARCHAR(80)  NOT NULL,
    processado_em TIMESTAMPTZ  NOT NULL
);

-- Consulta usada na Etapa 10 para limpar registros antigos: passada a janela de
-- retentativa do gateway, guardar o evento deixa de ter proposito.
CREATE INDEX eventos_processados_por_data ON eventos_processados (processado_em);
