-- Eventos de dominio esperando publicacao.
--
-- Esta tabela e o coracao do projeto. Ela existe porque gravar no banco e
-- publicar na fila sao escritas em sistemas que NAO compartilham transacao:
--
--   publicar e depois commitar -> o commit falha, e ha evento sobre algo que
--                                 nao aconteceu
--   commitar e depois publicar -> a publicacao falha, e o fato aconteceu sem
--                                 ninguem saber
--
-- Gravando o evento aqui, na mesma transacao do fato, so existe UMA escrita.
-- Um processo separado le esta tabela e publica.

CREATE TABLE outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Gerado por nos e enviado na mensagem: e a chave de idempotencia de quem
    -- consome. Republicar a mesma linha produz a mesma chave, e e assim que o
    -- consumidor reconhece a repeticao.
    id_evento   VARCHAR(36)  NOT NULL UNIQUE,
    tipo        VARCHAR(80)  NOT NULL,
    agregado_id VARCHAR(60)  NOT NULL,
    payload     TEXT         NOT NULL,
    criado_em   TIMESTAMPTZ  NOT NULL,
    -- Nulo enquanto pendente. So e preenchido depois que o broker CONFIRMA o
    -- recebimento — nao quando a chamada de publicacao retorna.
    publicado_em TIMESTAMPTZ,
    tentativas  INTEGER      NOT NULL DEFAULT 0,
    ultimo_erro VARCHAR(500),

    CONSTRAINT outbox_tentativas_nao_negativas CHECK (tentativas >= 0)
);

-- Indice parcial: so as linhas pendentes interessam ao worker, e elas sao uma
-- fracao minima da tabela depois de algum tempo de operacao. Um indice sobre a
-- coluna inteira cresceria com o historico sem servir para nada.
CREATE INDEX outbox_pendentes ON outbox (criado_em) WHERE publicado_em IS NULL;
