-- Idempotencia do lado de quem consome a fila.
--
-- A entrega do RabbitMQ tambem e "pelo menos uma vez": uma mensagem confirmada
-- tarde demais, ou um consumidor que morre depois de processar e antes do ack,
-- produz reentrega. Sem esta tabela, o estoque baixaria duas vezes e o cliente
-- receberia dois avisos.
--
-- A chave e o PAR (mensagem, consumidor), nao so a mensagem: o mesmo evento
-- pedido.pago vai para a fila de estoque E para a de notificacoes. Se a chave
-- fosse so o id da mensagem, o primeiro consumidor a processar bloquearia o
-- segundo, e o cliente nunca seria avisado.
CREATE TABLE mensagens_consumidas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mensagem  VARCHAR(80) NOT NULL,
    consumidor   VARCHAR(80) NOT NULL,
    consumida_em TIMESTAMPTZ NOT NULL,

    CONSTRAINT mensagens_consumidas_unicas UNIQUE (id_mensagem, consumidor)
);

-- Avisos enviados ao cliente.
--
-- Neste projeto o "envio" e a propria gravacao desta linha: nao ha servidor de
-- e-mail, e simular um traria complexidade sem ensinar nada novo. O que a
-- tabela cumpre e o papel que importa — ser um efeito colateral OBSERVAVEL, que
-- um teste consegue contar para provar que a entrega duplicada nao gerou dois
-- avisos.
CREATE TABLE notificacoes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id  BIGINT       NOT NULL REFERENCES pedidos (id),
    usuario_id BIGINT       NOT NULL REFERENCES usuarios (id),
    tipo       VARCHAR(60)  NOT NULL,
    mensagem   VARCHAR(300) NOT NULL,
    criada_em  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX notificacoes_por_pedido ON notificacoes (pedido_id);
